/* eslint-enable */

export function getIssueCreate(timestamp: any) {
  return {
    changelog: {
      id: '1670930',
      items: [
        {
          field: 'priority',
          fieldId: 'priority',
          fieldtype: 'jira',
          from: null,
          fromString: null,
          to: '3',
          toString: 'Medium',
        },
        {
          field: 'reporter',
          fieldId: 'reporter',
          fieldtype: 'jira',
          from: null,
          fromString: null,
          tmpFromAccountId: null,
          tmpToAccountId: '5e93fd859a3bf20c2d94bd3b',
          to: '5e93fd859a3bf20c2d94bd3b',
          toString: 'Narendra Vishwakarma',
        },
        {
          field: 'Status',
          fieldId: 'status',
          fieldtype: 'jira',
          from: null,
          fromString: null,
          to: '1',
          toString: 'ToDo',
        },
        {
          field: 'summary',
          fieldId: 'summary',
          fieldtype: 'jira',
          from: null,
          fromString: null,
          to: null,
          toString: 'Parent Task [No subtasks]',
        },
      ],
    },
    issue: {
      fields: {
        aggregateprogress: {
          progress: 0,
          total: 0,
        },
        aggregatetimeestimate: null,
        aggregatetimeoriginalestimate: null,
        aggregatetimespent: null,
        assignee: null,
        attachment: [],
        components: [],
        created: '2024-05-21T09:18:58.187+0100',
        creator: {
          accountId: '5e93fd859a3bf20c2d94bd3b',
          accountType: 'atlassian',
          active: true,
          avatarUrls: {
            '16x16':
              'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
            '24x24':
              'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
            '32x32':
              'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
            '48x48':
              'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
          },
          displayName: 'Narendra Vishwakarma',
          self: 'https://studiographene.atlassian.net/rest/api/2/user?accountId=5e93fd859a3bf20c2d94bd3b',
          timeZone: 'Europe/London',
        },
        customfield_10000: null,
        customfield_10001: null,
        customfield_10003: null,
        customfield_10004: null,
        customfield_10007: [
          {
            boardId: 534,
            endDate: '2024-05-10T09:17:25.000Z',
            goal: '',
            id: 1764,
            name: 'PT Sprint 2',
            startDate: '2024-04-12T09:23:00.269Z',
            state: 'active',
          },
        ],
        customfield_10008: null,
        customfield_10012: '2|r03c1j:',
        customfield_10100: null,
        customfield_10200: null,
        customfield_10400: null,
        customfield_10500: {
          hasEpicLinkFieldDependency: false,
          nonEditableReason: {
            message: 'To set an epic as the parent, use the epic link instead',
            reason: 'EPIC_LINK_SHOULD_BE_USED',
          },
          showField: false,
        },
        customfield_10600: '{}',
        customfield_10700: null,
        customfield_10800: null,
        customfield_10900: null,
        customfield_10901: [],
        customfield_10902: null,
        customfield_10903: null,
        customfield_10904: null,
        customfield_10905: null,
        customfield_10906: null,
        customfield_11026: null,
        customfield_11029: null,
        customfield_11032: null,
        customfield_11033: null,
        customfield_11034: null,
        customfield_11035: null,
        customfield_11036: null,
        customfield_11037: null,
        customfield_11038: null,
        customfield_11039: null,
        customfield_11040: null,
        customfield_11041: null,
        customfield_11042: null,
        customfield_11043: null,
        customfield_11044: null,
        customfield_11045: null,
        customfield_11046: null,
        customfield_11047: null,
        customfield_11048: null,
        customfield_11049: null,
        customfield_11050: null,
        customfield_11051: null,
        customfield_11052: null,
        customfield_11053: null,
        customfield_11055: null,
        customfield_11058: null,
        customfield_11061: null,
        customfield_11062: null,
        customfield_11063: null,
        customfield_11064: null,
        customfield_11065: null,
        customfield_11066: null,
        customfield_11067: null,
        customfield_11068: null,
        customfield_11069: null,
        customfield_11070: null,
        customfield_11071: null,
        customfield_11072: null,
        customfield_11073: null,
        customfield_11074: null,
        customfield_11075: null,
        customfield_11076: null,
        customfield_11077: null,
        customfield_11078: null,
        customfield_11079: null,
        customfield_11080: null,
        customfield_11082: null,
        customfield_11083: [],
        customfield_11084: null,
        customfield_11085: null,
        customfield_11086: null,
        customfield_11087: null,
        customfield_11088: null,
        customfield_11089: null,
        customfield_11090: null,
        customfield_11091: null,
        customfield_11092: null,
        customfield_11093: null,
        customfield_11094: null,
        customfield_11095: null,
        customfield_11096: null,
        customfield_11097: null,
        customfield_11098: null,
        customfield_11099: null,
        customfield_11102: null,
        customfield_11138: null,
        customfield_11139: null,
        customfield_11140: null,
        customfield_11141: null,
        customfield_11142: null,
        customfield_11143: null,
        customfield_11144: null,
        customfield_11145: null,
        customfield_11179: null,
        customfield_11180: null,
        customfield_11181: null,
        customfield_11182: null,
        customfield_11183: null,
        customfield_11217: null,
        customfield_11220: null,
        customfield_11221: null,
        description: null,
        duedate: null,
        environment: null,
        fixVersions: [],
        issuelinks: [],
        issuerestriction: {
          issuerestrictions: {},
          shouldDisplay: false,
        },
        issuetype: {
          avatarId: 10318,
          description: 'A task that needs to be done.',
          hierarchyLevel: 0,
          iconUrl:
            'https://studiographene.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10318?size=medium',
          id: '3',
          name: 'Task',
          self: 'https://studiographene.atlassian.net/rest/api/2/issuetype/3',
          subtask: false,
        },
        labels: [],
        lastViewed: null,
        priority: {
          iconUrl: 'https://studiographene.atlassian.net/images/icons/priorities/medium.svg',
          id: '3',
          name: 'Medium',
          self: 'https://studiographene.atlassian.net/rest/api/2/priority/3',
        },
        progress: {
          progress: 0,
          total: 0,
        },
        project: {
          avatarUrls: {
            '16x16':
              'https://studiographene.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/12461?size=xsmall',
            '24x24':
              'https://studiographene.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/12461?size=small',
            '32x32':
              'https://studiographene.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/12461?size=medium',
            '48x48':
              'https://studiographene.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/12461',
          },
          id: '14128',
          key: 'PT',
          name: 'Pulse testing',
          projectTypeKey: 'software',
          self: 'https://studiographene.atlassian.net/rest/api/2/project/14128',
          simplified: false,
        },
        reporter: {
          accountId: '5e93fd859a3bf20c2d94bd3b',
          accountType: 'atlassian',
          active: true,
          avatarUrls: {
            '16x16':
              'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
            '24x24':
              'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
            '32x32':
              'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
            '48x48':
              'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
          },
          displayName: 'Narendra Vishwakarma',
          self: 'https://studiographene.atlassian.net/rest/api/2/user?accountId=5e93fd859a3bf20c2d94bd3b',
          timeZone: 'Europe/London',
        },
        resolution: null,
        resolutiondate: null,
        security: null,
        status: {
          description: 'The issue is open and ready for the assignee to start work on it.',
          iconUrl: 'https://studiographene.atlassian.net/images/icons/statuses/open.png',
          id: '1',
          name: 'ToDo',
          self: 'https://studiographene.atlassian.net/rest/api/2/status/1',
          statusCategory: {
            colorName: 'blue-gray',
            id: 2,
            key: 'new',
            name: 'New',
            self: 'https://studiographene.atlassian.net/rest/api/2/statuscategory/2',
          },
        },
        statuscategorychangedate: '2024-05-21T09:18:58.623+0100',
        subtasks: [],
        summary: 'Parent Task [No subtasks]',
        timeestimate: null,
        timeoriginalestimate: null,
        timespent: null,
        timetracking: {},
        updated: '2024-05-21T09:18:58.187+0100',
        versions: [],
        votes: {
          hasVoted: false,
          self: 'https://studiographene.atlassian.net/rest/api/2/issue/PT-13/votes',
          votes: 0,
        },
        watches: {
          isWatching: true,
          self: 'https://studiographene.atlassian.net/rest/api/2/issue/PT-13/watchers',
          watchCount: 0,
        },
        workratio: -1,
      },
      id: '118738',
      key: 'PT-13',
      self: 'https://studiographene.atlassian.net/rest/api/2/118738',
    },
    issue_event_type_name: 'issue_created',
    timestamp: timestamp,
    user: {
      accountId: '5e93fd859a3bf20c2d94bd3b',
      accountType: 'atlassian',
      active: true,
      avatarUrls: {
        '16x16':
          'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
        '24x24':
          'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
        '32x32':
          'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
        '48x48':
          'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
      },
      displayName: 'Narendra Vishwakarma',
      self: 'https://studiographene.atlassian.net/rest/api/2/user?accountId=5e93fd859a3bf20c2d94bd3b',
      timeZone: 'Europe/London',
    },
    webhookEvent: 'jira:issue_created',
  };
}
// @ts-ignore
export function getChangelog(from, to, timestamp, issueId?, issuetype = 'Task') {
  return {
    changelog: {
      id: '1670936',
      items: [
        {
          field: 'status',
          fieldId: 'status',
          fieldtype: 'jira',
          from: from,
          fromString: 'ToDo',
          to: to,
          toString: 'In Progress',
        },
      ],
      issuetype,
      issueId: issueId ?? '',
      timestamp: timestamp,
    },
    issue: {
      fields: {
        aggregateprogress: {
          progress: 0,
          total: 0,
        },
        aggregatetimeestimate: null,
        aggregatetimeoriginalestimate: null,
        aggregatetimespent: null,
        assignee: null,
        attachment: [],
        components: [],
        created: '2024-05-21T09:18:58.187+0100',
        creator: {
          accountId: '5e93fd859a3bf20c2d94bd3b',
          accountType: 'atlassian',
          active: true,
          avatarUrls: {
            '16x16':
              'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
            '24x24':
              'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
            '32x32':
              'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
            '48x48':
              'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
          },
          displayName: 'Narendra Vishwakarma',
          self: 'https://studiographene.atlassian.net/rest/api/2/user?accountId=5e93fd859a3bf20c2d94bd3b',
          timeZone: 'Europe/London',
        },
        customfield_10000: null,
        customfield_10001: null,
        customfield_10003: null,
        customfield_10004: null,
        customfield_10007: [
          {
            boardId: 534,
            endDate: '2024-05-10T09:17:25.000Z',
            goal: '',
            id: 1764,
            name: 'PT Sprint 2',
            startDate: '2024-04-12T09:23:00.269Z',
            state: 'active',
          },
        ],
        customfield_10008: null,
        customfield_10012: '2|r03c1j:',
        customfield_10100: null,
        customfield_10200: null,
        customfield_10400: null,
        customfield_10500: {
          hasEpicLinkFieldDependency: false,
          nonEditableReason: {
            message: 'To set an epic as the parent, use the epic link instead',
            reason: 'EPIC_LINK_SHOULD_BE_USED',
          },
          showField: false,
        },
        customfield_10600: '{}',
        customfield_10700: null,
        customfield_10800: null,
        customfield_10900: null,
        customfield_10901: [],
        customfield_10902: null,
        customfield_10903: null,
        customfield_10904: null,
        customfield_10905: null,
        customfield_10906: null,
        customfield_11026: null,
        customfield_11029: null,
        customfield_11032: null,
        customfield_11033: null,
        customfield_11034: null,
        customfield_11035: null,
        customfield_11036: null,
        customfield_11037: null,
        customfield_11038: null,
        customfield_11039: null,
        customfield_11040: null,
        customfield_11041: null,
        customfield_11042: null,
        customfield_11043: null,
        customfield_11044: null,
        customfield_11045: null,
        customfield_11046: null,
        customfield_11047: null,
        customfield_11048: null,
        customfield_11049: null,
        customfield_11050: null,
        customfield_11051: null,
        customfield_11052: null,
        customfield_11053: null,
        customfield_11055: null,
        customfield_11058: null,
        customfield_11061: null,
        customfield_11062: null,
        customfield_11063: null,
        customfield_11064: null,
        customfield_11065: null,
        customfield_11066: null,
        customfield_11067: null,
        customfield_11068: null,
        customfield_11069: null,
        customfield_11070: null,
        customfield_11071: null,
        customfield_11072: null,
        customfield_11073: null,
        customfield_11074: null,
        customfield_11075: null,
        customfield_11076: null,
        customfield_11077: null,
        customfield_11078: null,
        customfield_11079: null,
        customfield_11080: null,
        customfield_11082: null,
        customfield_11083: [],
        customfield_11084: null,
        customfield_11085: null,
        customfield_11086: null,
        customfield_11087: null,
        customfield_11088: null,
        customfield_11089: null,
        customfield_11090: null,
        customfield_11091: null,
        customfield_11092: null,
        customfield_11093: null,
        customfield_11094: null,
        customfield_11095: null,
        customfield_11096: null,
        customfield_11097: null,
        customfield_11098: null,
        customfield_11099: null,
        customfield_11102: null,
        customfield_11138: null,
        customfield_11139: null,
        customfield_11140: null,
        customfield_11141: null,
        customfield_11142: null,
        customfield_11143: null,
        customfield_11144: null,
        customfield_11145: null,
        customfield_11179: null,
        customfield_11180: null,
        customfield_11181: null,
        customfield_11182: null,
        customfield_11183: null,
        customfield_11217: null,
        customfield_11220: null,
        customfield_11221: null,
        description: null,
        duedate: null,
        environment: null,
        fixVersions: [],
        issuelinks: [],
        issuerestriction: {
          issuerestrictions: {},
          shouldDisplay: false,
        },
        issuetype: {
          avatarId: 10318,
          description: 'A task that needs to be done.',
          hierarchyLevel: 0,
          iconUrl:
            'https://studiographene.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10318?size=medium',
          id: '3',
          name: issuetype,
          self: 'https://studiographene.atlassian.net/rest/api/2/issuetype/3',
          subtask: false,
        },
        labels: [],
        lastViewed: '2024-05-21T09:19:07.879+0100',
        priority: {
          iconUrl: 'https://studiographene.atlassian.net/images/icons/priorities/medium.svg',
          id: '3',
          name: 'Medium',
          self: 'https://studiographene.atlassian.net/rest/api/2/priority/3',
        },
        progress: {
          progress: 0,
          total: 0,
        },
        project: {
          avatarUrls: {
            '16x16':
              'https://studiographene.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/12461?size=xsmall',
            '24x24':
              'https://studiographene.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/12461?size=small',
            '32x32':
              'https://studiographene.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/12461?size=medium',
            '48x48':
              'https://studiographene.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/12461',
          },
          id: '14128',
          key: 'PT',
          name: 'Pulse testing',
          projectTypeKey: 'software',
          self: 'https://studiographene.atlassian.net/rest/api/2/project/14128',
          simplified: false,
        },
        reporter: {
          accountId: '5e93fd859a3bf20c2d94bd3b',
          accountType: 'atlassian',
          active: true,
          avatarUrls: {
            '16x16':
              'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
            '24x24':
              'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
            '32x32':
              'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
            '48x48':
              'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
          },
          displayName: 'Narendra Vishwakarma',
          self: 'https://studiographene.atlassian.net/rest/api/2/user?accountId=5e93fd859a3bf20c2d94bd3b',
          timeZone: 'Europe/London',
        },
        resolution: null,
        resolutiondate: null,
        security: null,
        status: {
          description: 'This issue is being actively worked on at the moment by the assignee.',
          iconUrl: 'https://studiographene.atlassian.net/images/icons/statuses/inprogress.png',
          id: '3',
          name: 'In Progress',
          self: 'https://studiographene.atlassian.net/rest/api/2/status/3',
          statusCategory: {
            colorName: 'yellow',
            id: 4,
            key: 'indeterminate',
            name: 'In Progress',
            self: 'https://studiographene.atlassian.net/rest/api/2/statuscategory/4',
          },
        },
        statuscategorychangedate: '2024-05-21T09:27:02.107+0100',
        subtasks: [],
        summary: 'Parent Task [No subtasks]',
        timeestimate: null,
        timeoriginalestimate: null,
        timespent: null,
        timetracking: {},
        updated: '2024-05-21T09:27:02.107+0100',
        versions: [],
        votes: {
          hasVoted: false,
          self: 'https://studiographene.atlassian.net/rest/api/2/issue/PT-13/votes',
          votes: 0,
        },
        watches: {
          isWatching: true,
          self: 'https://studiographene.atlassian.net/rest/api/2/issue/PT-13/watchers',
          watchCount: 1,
        },
        workratio: -1,
      },
      id: '118738',
      key: 'PT-13',
      self: 'https://studiographene.atlassian.net/rest/api/2/118738',
    },
    issue_event_type_name: 'issue_generic',
    timestamp: timestamp,
    user: {
      accountId: '5e93fd859a3bf20c2d94bd3b',
      accountType: 'atlassian',
      active: true,
      avatarUrls: {
        '16x16':
          'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
        '24x24':
          'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
        '32x32':
          'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
        '48x48':
          'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
      },
      displayName: 'Narendra Vishwakarma',
      self: 'https://studiographene.atlassian.net/rest/api/2/user?accountId=5e93fd859a3bf20c2d94bd3b',
      timeZone: 'Europe/London',
    },
    webhookEvent: 'jira:issue_updated',
  };
}
// @ts-ignore
export function getAssigneeAdded(to, toString) {
  return {
    body: {
      changelog: {
        id: '1670941',
        items: [
          {
            field: 'assignee',
            fieldId: 'assignee',
            fieldtype: 'jira',
            from: null,
            fromString: null,
            tmpFromAccountId: null,
            tmpToAccountId: to,
            to,
            toString,
          },
        ],
      },
      issue: {
        fields: {
          aggregateprogress: {
            progress: 0,
            total: 0,
          },
          aggregatetimeestimate: null,
          aggregatetimeoriginalestimate: null,
          aggregatetimespent: null,
          assignee: {
            accountId: '5e93fd859a3bf20c2d94bd3b',
            accountType: 'atlassian',
            active: true,
            avatarUrls: {
              '16x16':
                'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
              '24x24':
                'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
              '32x32':
                'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
              '48x48':
                'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
            },
            displayName: 'Narendra Vishwakarma',
            self: 'https://studiographene.atlassian.net/rest/api/2/user?accountId=5e93fd859a3bf20c2d94bd3b',
            timeZone: 'Europe/London',
          },
          attachment: [],
          components: [],
          created: '2024-05-21T09:18:58.187+0100',
          creator: {
            accountId: '5e93fd859a3bf20c2d94bd3b',
            accountType: 'atlassian',
            active: true,
            avatarUrls: {
              '16x16':
                'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
              '24x24':
                'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
              '32x32':
                'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
              '48x48':
                'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
            },
            displayName: 'Narendra Vishwakarma',
            self: 'https://studiographene.atlassian.net/rest/api/2/user?accountId=5e93fd859a3bf20c2d94bd3b',
            timeZone: 'Europe/London',
          },
          customfield_10000: null,
          customfield_10001: null,
          customfield_10003: null,
          customfield_10004: null,
          customfield_10007: [
            {
              boardId: 534,
              endDate: '2024-05-10T09:17:25.000Z',
              goal: '',
              id: 1764,
              name: 'PT Sprint 2',
              startDate: '2024-04-12T09:23:00.269Z',
              state: 'active',
            },
          ],
          customfield_10008: null,
          customfield_10012: '2|r03c1j:',
          customfield_10100: null,
          customfield_10200: null,
          customfield_10400: null,
          customfield_10500: {
            hasEpicLinkFieldDependency: false,
            nonEditableReason: {
              message: 'To set an epic as the parent, use the epic link instead',
              reason: 'EPIC_LINK_SHOULD_BE_USED',
            },
            showField: false,
          },
          customfield_10600: '{}',
          customfield_10700: null,
          customfield_10800: null,
          customfield_10900: null,
          customfield_10901: [],
          customfield_10902: null,
          customfield_10903: null,
          customfield_10904: null,
          customfield_10905: null,
          customfield_10906: null,
          customfield_11026: null,
          customfield_11029: null,
          customfield_11032: null,
          customfield_11033: null,
          customfield_11034: null,
          customfield_11035: null,
          customfield_11036: null,
          customfield_11037: null,
          customfield_11038: null,
          customfield_11039: null,
          customfield_11040: null,
          customfield_11041: null,
          customfield_11042: null,
          customfield_11043: null,
          customfield_11044: null,
          customfield_11045: null,
          customfield_11046: null,
          customfield_11047: null,
          customfield_11048: null,
          customfield_11049: null,
          customfield_11050: null,
          customfield_11051: null,
          customfield_11052: null,
          customfield_11053: null,
          customfield_11055: null,
          customfield_11058: null,
          customfield_11061: null,
          customfield_11062: null,
          customfield_11063: null,
          customfield_11064: null,
          customfield_11065: null,
          customfield_11066: null,
          customfield_11067: null,
          customfield_11068: null,
          customfield_11069: null,
          customfield_11070: null,
          customfield_11071: null,
          customfield_11072: null,
          customfield_11073: null,
          customfield_11074: null,
          customfield_11075: null,
          customfield_11076: null,
          customfield_11077: null,
          customfield_11078: null,
          customfield_11079: null,
          customfield_11080: null,
          customfield_11082: null,
          customfield_11083: [],
          customfield_11084: null,
          customfield_11085: null,
          customfield_11086: null,
          customfield_11087: null,
          customfield_11088: null,
          customfield_11089: null,
          customfield_11090: null,
          customfield_11091: null,
          customfield_11092: null,
          customfield_11093: null,
          customfield_11094: null,
          customfield_11095: null,
          customfield_11096: null,
          customfield_11097: null,
          customfield_11098: null,
          customfield_11099: null,
          customfield_11102: null,
          customfield_11138: null,
          customfield_11139: null,
          customfield_11140: null,
          customfield_11141: null,
          customfield_11142: null,
          customfield_11143: null,
          customfield_11144: null,
          customfield_11145: null,
          customfield_11179: null,
          customfield_11180: null,
          customfield_11181: null,
          customfield_11182: null,
          customfield_11183: null,
          customfield_11217: null,
          customfield_11220: null,
          customfield_11221: null,
          description: null,
          duedate: null,
          environment: null,
          fixVersions: [],
          issuelinks: [],
          issuerestriction: {
            issuerestrictions: {},
            shouldDisplay: false,
          },
          issuetype: {
            avatarId: 10318,
            description: 'A task that needs to be done.',
            hierarchyLevel: 0,
            iconUrl:
              'https://studiographene.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10318?size=medium',
            id: '3',
            name: 'Task',
            self: 'https://studiographene.atlassian.net/rest/api/2/issuetype/3',
            subtask: false,
          },
          labels: [],
          lastViewed: '2024-05-21T09:19:07.879+0100',
          priority: {
            iconUrl: 'https://studiographene.atlassian.net/images/icons/priorities/medium.svg',
            id: '3',
            name: 'Medium',
            self: 'https://studiographene.atlassian.net/rest/api/2/priority/3',
          },
          progress: {
            progress: 0,
            total: 0,
          },
          project: {
            avatarUrls: {
              '16x16':
                'https://studiographene.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/12461?size=xsmall',
              '24x24':
                'https://studiographene.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/12461?size=small',
              '32x32':
                'https://studiographene.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/12461?size=medium',
              '48x48':
                'https://studiographene.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/12461',
            },
            id: '14128',
            key: 'PT',
            name: 'Pulse testing',
            projectTypeKey: 'software',
            self: 'https://studiographene.atlassian.net/rest/api/2/project/14128',
            simplified: false,
          },
          reporter: {
            accountId: '5e93fd859a3bf20c2d94bd3b',
            accountType: 'atlassian',
            active: true,
            avatarUrls: {
              '16x16':
                'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
              '24x24':
                'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
              '32x32':
                'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
              '48x48':
                'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
            },
            displayName: 'Narendra Vishwakarma',
            self: 'https://studiographene.atlassian.net/rest/api/2/user?accountId=5e93fd859a3bf20c2d94bd3b',
            timeZone: 'Europe/London',
          },
          resolution: null,
          resolutiondate: null,
          security: null,
          status: {
            description: 'This issue is being actively worked on at the moment by the assignee.',
            iconUrl: 'https://studiographene.atlassian.net/images/icons/statuses/inprogress.png',
            id: '3',
            name: 'In Progress',
            self: 'https://studiographene.atlassian.net/rest/api/2/status/3',
            statusCategory: {
              colorName: 'yellow',
              id: 4,
              key: 'indeterminate',
              name: 'In Progress',
              self: 'https://studiographene.atlassian.net/rest/api/2/statuscategory/4',
            },
          },
          statuscategorychangedate: '2024-05-21T09:27:02.107+0100',
          subtasks: [],
          summary: 'Parent Task [No subtasks]',
          timeestimate: null,
          timeoriginalestimate: null,
          timespent: null,
          timetracking: {},
          updated: '2024-05-21T09:29:45.939+0100',
          versions: [],
          votes: {
            hasVoted: false,
            self: 'https://studiographene.atlassian.net/rest/api/2/issue/PT-13/votes',
            votes: 0,
          },
          watches: {
            isWatching: true,
            self: 'https://studiographene.atlassian.net/rest/api/2/issue/PT-13/watchers',
            watchCount: 1,
          },
          workratio: -1,
        },
        id: '118738',
        key: 'PT-13',
        self: 'https://studiographene.atlassian.net/rest/api/2/118738',
      },
      issue_event_type_name: 'issue_assigned',
      timestamp: 1716280185962,
      user: {
        accountId: '5e93fd859a3bf20c2d94bd3b',
        accountType: 'atlassian',
        active: true,
        avatarUrls: {
          '16x16':
            'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
          '24x24':
            'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
          '32x32':
            'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
          '48x48':
            'https://secure.gravatar.com/avatar/b253b3fcb280614f79274b4b2ab515cc?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FNV-2.png',
        },
        displayName: 'Narendra Vishwakarma',
        self: 'https://studiographene.atlassian.net/rest/api/2/user?accountId=5e93fd859a3bf20c2d94bd3b',
        timeZone: 'Europe/London',
      },
      webhookEvent: 'jira:issue_updated',
    },
    level: 'info',
    message: 'webhook.handler.received',
    organization: 'studiographene',
  };
}

// @ts-ignore
export const getTimestamp = (dateString) => new Date(dateString).getTime();

export const Status: Record<string, number> = {
  To_Do: 1,
  In_Progress: 2,
  Ready_For_Review: 3,
  Code_Review: 4,
  Dev_Complete: 5,
  Ready_For_QA: 6,
  QA_In_Progress: 7,
  QA_Failed: 8,
  QA_Pass_Deploy: 9,
  Done: 10,
  Rejected: 11,
  Blocked: 12,
};

// @ts-ignore
export function format(data) {
  const { issue } = data;
  const isSubtask = issue.fields.issuetype.subtask;
  // console.log(isSubtask);
  const dataFromEsb = getDatafromEsb(issue.fields.parent?.id);
  // if (isSubtask) {
  //   const newSubtask = formatSubtask(issue, {
  //     ...data.changelog,
  //     timestamp: data.timestamp,
  //   });
  //   dataFromEsb?.subtasks.push(newSubtask as never);
  // }

  return {
    issueId: dataFromEsb?.issueId ?? issue.id,
    sprintId: dataFromEsb?.sprintId ?? issue.fields.customfield_10007[0].id,
    subtasks: dataFromEsb?.subtasks ?? issue.fields.subtasks,
    organizationId: dataFromEsb?.orgId ?? '12345',
    issueType: dataFromEsb?.issueType ?? issue.fields.issuetype.name,
    projectId: dataFromEsb?.projectId ?? issue.fields.project.id,
    projectKey: dataFromEsb?.projectKey ?? issue.fields.project.key,
    assignee: dataFromEsb?.assignees ?? issue.fields.assignee,
    title: dataFromEsb?.title ?? issue.fields.summary,
    issueKey: dataFromEsb?.issueKey ?? issue.key,
    changelog: {
      ...data.changelog,
      timestamp: data.timestamp,
      issuetype: issue.fields.issuetype.name,
    },
    isDeleted: data.isDeleted,
    deletedAt: data.deletedAt,
  };
}

// @ts-ignore
function getDatafromEsb(id) {
  const data = {
    development: {
      coding: 0,
      pickup: 0,
      review: 0,
      handover: 0,
      total: 0,
    },
    qa: {
      pickup: 0,
      testing: 0,
      total: 0,
    },
    deployment: {
      total: 0,
    },
    history: [],
    assignees: [],
    issueId: '116277',
    issueKey: 'PT-13',
    orgId: '12345',
    projectId: '14128',
    projectKey: 'PT',
    sprintId: 1764,
    subtasks: [],
    title: 'Parent Task [No subtasks]',
    issueType: 'Task',
  };
  if (data.issueId == id) {
    return data;
  }
  return;
}

// @ts-ignore
export function formatSubtask(issue, changelog) {
  return {
    issueId: issue.id,
    assignees: issue.assignee,
    title: issue.title,
    issueKey: issue.issueKey,
    changelog,
  };
}

// @ts-ignore
export function createIssueWithSubtask(timestamp, subtaskId, subtaskKey) {
  return {
    changelog: {
      id: '1670930',
      items: [
        {
          field: 'priority',
          fieldId: 'priority',
          fieldtype: 'jira',
          from: null,
          fromString: null,
          to: '3',
          toString: 'Medium',
        },
        {
          field: 'reporter',
          fieldId: 'reporter',
          fieldtype: 'jira',
          from: null,
          fromString: null,
          tmpFromAccountId: null,
          tmpToAccountId: '5e93fd859a3bf20c2d94bd3b',
          to: '5e93fd859a3bf20c2d94bd3b',
          toString: 'Narendra Vishwakarma',
        },
        {
          field: 'Status',
          fieldId: 'status',
          fieldtype: 'jira',
          from: null,
          fromString: null,
          to: '1',
          toString: 'ToDo',
        },
        {
          field: 'summary',
          fieldId: 'summary',
          fieldtype: 'jira',
          from: null,
          fromString: null,
          to: null,
          toString: 'Parent Task [No subtasks]',
        },
      ],
    },
    issue: {
      fields: {
        aggregateprogress: {
          progress: 0,
          total: 0,
        },
        aggregatetimeestimate: null,
        aggregatetimeoriginalestimate: null,
        aggregatetimespent: null,
        assignee: null,
        attachment: [],
        components: [],
        created: '2024-04-12T10:58:27.795+0100',
        creator: {
          accountId: '630c805f6a8bb4eda6768bef',
          accountType: 'atlassian',
          active: true,
        },
        customfield_10000: null,
        customfield_10001: null,
        customfield_10003: null,
        customfield_10004: null,
        customfield_10007: [
          {
            boardId: 534,
            endDate: '2024-05-10T09:17:25.000Z',
            goal: '',
            id: 1764,
            name: 'PT Sprint 2',
            startDate: '2024-04-12T09:23:00.269Z',
            state: 'active',
          },
        ],
        customfield_10008: null,
        customfield_10012: '2|r02xnz:',
        customfield_10100: null,
        customfield_10200: null,
        customfield_10400: null,
        customfield_10500: {
          hasEpicLinkFieldDependency: false,
          nonEditableReason: {
            message: 'To set the parent for a sub-task, use the sub-task link.',
            reason: 'SUBTASK_LINK_SHOULD_BE_USED',
          },
          showField: false,
        },
        customfield_10600: '{}',
        customfield_10700: null,
        customfield_10800: null,
        customfield_10900: null,
        customfield_10901: [],
        customfield_10902: null,
        customfield_10903: null,
        customfield_10904: null,
        customfield_10905: null,
        customfield_10906: null,
        customfield_11026: null,
        customfield_11029: null,
        customfield_11032: null,
        customfield_11033: null,
        customfield_11034: null,
        customfield_11035: null,
        customfield_11036: null,
        customfield_11037: null,
        customfield_11038: null,
        customfield_11039: null,
        customfield_11040: null,
        customfield_11041: null,
        customfield_11042: null,
        customfield_11043: null,
        customfield_11044: null,
        customfield_11045: null,
        customfield_11046: null,
        customfield_11047: null,
        customfield_11048: null,
        customfield_11049: null,
        customfield_11050: null,
        customfield_11051: null,
        customfield_11052: null,
        customfield_11053: null,
        customfield_11055: null,
        customfield_11058: null,
        customfield_11061: null,
        customfield_11062: null,
        customfield_11063: null,
        customfield_11064: null,
        customfield_11065: null,
        customfield_11066: null,
        customfield_11067: null,
        customfield_11068: null,
        customfield_11069: null,
        customfield_11070: null,
        customfield_11071: null,
        customfield_11072: null,
        customfield_11073: null,
        customfield_11074: null,
        customfield_11075: null,
        customfield_11076: null,
        customfield_11077: null,
        customfield_11078: null,
        customfield_11079: null,
        customfield_11080: null,
        customfield_11082: null,
        customfield_11083: [],
        customfield_11084: null,
        customfield_11085: null,
        customfield_11086: null,
        customfield_11087: null,
        customfield_11088: null,
        customfield_11089: null,
        customfield_11090: null,
        customfield_11091: null,
        customfield_11092: null,
        customfield_11093: null,
        customfield_11094: null,
        customfield_11095: null,
        customfield_11096: null,
        customfield_11097: null,
        customfield_11098: null,
        customfield_11099: null,
        customfield_11102: null,
        customfield_11138: null,
        customfield_11139: null,
        customfield_11140: null,
        customfield_11141: null,
        customfield_11142: null,
        customfield_11143: null,
        customfield_11144: null,
        customfield_11145: null,
        customfield_11179: null,
        customfield_11180: null,
        customfield_11181: null,
        customfield_11182: null,
        customfield_11183: null,
        customfield_11217: null,
        customfield_11220: null,
        customfield_11221: null,
        description: null,
        duedate: null,
        environment: null,
        fixVersions: [],
        issuelinks: [
          {
            id: '94922',
            inwardIssue: {
              fields: {
                issuetype: {
                  avatarId: 10318,
                  description: 'A small, distinct piece of work.',
                  hierarchyLevel: 0,
                  iconUrl:
                    'https://studiographene.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10318?size=medium',
                  id: '3',
                  name: 'Task',
                  self: 'https://studiographene.atlassian.net/rest/api/2/issuetype/3',
                  subtask: false,
                },
                priority: {
                  iconUrl:
                    'https://studiographene.atlassian.net/images/icons/priorities/lowest.svg',
                  id: '5',
                  name: 'Lowest',
                  self: 'https://studiographene.atlassian.net/rest/api/2/priority/5',
                },
                status: {
                  description: '',
                  iconUrl: 'https://studiographene.atlassian.net/images/icons/statuses/generic.png',
                  id: '11905',
                  name: 'QA Failed',
                  self: 'https://studiographene.atlassian.net/rest/api/2/status/11905',
                  statusCategory: {
                    colorName: 'yellow',
                    id: 4,
                    key: 'indeterminate',
                    name: 'In Progress',
                    self: 'https://studiographene.atlassian.net/rest/api/2/statuscategory/4',
                  },
                },
                summary: 'ftp testing',
              },
              id: '117284',
              key: 'PT-9',
              self: 'https://studiographene.atlassian.net/rest/api/2/issue/117284',
            },
            self: 'https://studiographene.atlassian.net/rest/api/2/issueLink/94922',
            type: {
              id: '10402',
              inward: 'created by',
              name: 'Defect',
              outward: 'created',
              self: 'https://studiographene.atlassian.net/rest/api/2/issueLinkType/10402',
            },
          },
        ],
        issuerestriction: {
          issuerestrictions: {},
          shouldDisplay: false,
        },
        issuetype: {
          avatarId: 10316,
          description: 'The sub-task of the issue',
          hierarchyLevel: -1,
          iconUrl:
            'https://studiographene.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10316?size=medium',
          id: '5',
          name: 'Sub-task',
          self: 'https://studiographene.atlassian.net/rest/api/2/issuetype/5',
          subtask: true,
        },
        labels: ['FTP'],
        lastViewed: null,
        parent: {
          fields: {
            issuetype: {
              avatarId: 10315,
              description:
                'Created by Jira Agile - do not edit or delete. Issue type for a user story.',
              hierarchyLevel: 0,
              iconUrl:
                'https://studiographene.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium',
              id: '10001',
              name: 'Story',
              self: 'https://studiographene.atlassian.net/rest/api/2/issuetype/10001',
              subtask: false,
            },
            priority: {
              iconUrl: 'https://studiographene.atlassian.net/images/icons/priorities/medium.svg',
              id: '3',
              name: 'Medium',
              self: 'https://studiographene.atlassian.net/rest/api/2/priority/3',
            },
            status: {
              description: '',
              iconUrl: 'https://studiographene.atlassian.net/images/icons/statuses/generic.png',
              id: '11905',
              name: 'QA Failed',
              self: 'https://studiographene.atlassian.net/rest/api/2/status/11905',
              statusCategory: {
                colorName: 'yellow',
                id: 4,
                key: 'indeterminate',
                name: 'In Progress',
                self: 'https://studiographene.atlassian.net/rest/api/2/statuscategory/4',
              },
            },
            summary: 'this a story for subtasks',
          },
          id: '116277',
          key: 'PT-3',
          self: 'https://studiographene.atlassian.net/rest/api/2/issue/116277',
        },
        priority: {
          iconUrl: 'https://studiographene.atlassian.net/images/icons/priorities/medium.svg',
          id: '3',
          name: 'Medium',
          self: 'https://studiographene.atlassian.net/rest/api/2/priority/3',
        },
        progress: {
          progress: 0,
          total: 0,
        },
        project: {
          id: '14128',
          key: 'PT',
          name: 'Pulse testing',
          projectTypeKey: 'software',
          self: 'https://studiographene.atlassian.net/rest/api/2/project/14128',
          simplified: false,
        },
        reporter: {
          accountId: '630c805f6a8bb4eda6768bef',
          accountType: 'atlassian',
          active: true,

          displayName: 'Charchit Khandelwal',
          self: 'https://studiographene.atlassian.net/rest/api/2/user?accountId=630c805f6a8bb4eda6768bef',
          timeZone: 'Europe/London',
        },
        resolution: null,
        resolutiondate: null,
        security: null,
        status: {
          description: 'This issue is being actively worked on at the moment by the assignee.',
          iconUrl: 'https://studiographene.atlassian.net/images/icons/statuses/inprogress.png',
          id: '3',
          name: 'In Progress',
          self: 'https://studiographene.atlassian.net/rest/api/2/status/3',
          statusCategory: {
            colorName: 'yellow',
            id: 4,
            key: 'indeterminate',
            name: 'In Progress',
            self: 'https://studiographene.atlassian.net/rest/api/2/statuscategory/4',
          },
        },
        statuscategorychangedate: '2024-05-22T15:35:34.309+0100',
        subtasks: [],
        summary: 'helo3',
        timeestimate: null,
        timeoriginalestimate: null,
        timespent: null,
        timetracking: {},
        updated: '2024-05-22T15:35:34.308+0100',
        versions: [],
        votes: {
          hasVoted: false,
          self: 'https://studiographene.atlassian.net/rest/api/2/issue/PT-6/votes',
          votes: 0,
        },
        watches: {
          isWatching: true,
          self: 'https://studiographene.atlassian.net/rest/api/2/issue/PT-6/watchers',
          watchCount: 1,
        },
        workratio: -1,
      },
      id: subtaskId,
      key: subtaskKey,
      self: `https://studiographene.atlassian.net/rest/api/2/${subtaskId}`,
    },
    issue_event_type_name: 'issue_generic',
    timestamp: timestamp,
    user: {
      accountId: '630c805f6a8bb4eda6768bef',
      accountType: 'atlassian',
      active: true,

      displayName: 'Charchit Khandelwal',
      self: 'https://studiographene.atlassian.net/rest/api/2/user?accountId=630c805f6a8bb4eda6768bef',
      timeZone: 'Europe/London',
    },
    webhookEvent: 'jira:issue_updated',
  };
}

export enum issueType {
  SubTask = 'Sub-task',
  Task = 'Task',
  Bug = 'Bug',
  Story = 'Story',
}
