name: studiographene-ci

on:
  pull_request: {
    types: [opened, synchronize, reopened, closed]
  }
  issue_comment:

jobs:
  call-workflow:
    # uses: studiographene/github-action-workflows/.github/workflows/nodejs-ci.yml@master # if you want alternatively pin to tag version version
    uses: studiographene/github-action-workflows/.github/workflows/nodejs-ci.yml@feature/PX-2418 # Testing purpose
    secrets: inherit
    with:
      package_manager: pnpm
      build_command: pnpm run build
      lint_command: pnpm run lint
      excluded_jobs: docker
      run_dev_test: true
      dev_test_branch: master
      send_dev_test_coverage_report_to_pulse: true
      dev_test_coverage_report_directory: coverage
