name: studiographene-ci

on:
  pull_request: {}
  push:
    branches: ['master', 'dev']
  workflow_dispatch:

jobs:
  call-workflow:
    uses: studiographene/nodejs-ci/.github/workflows/ci.yml@master
    with:
      project_name: pulse-data-integration
      package_manager: pnpm
      build_command: pnpm run build --stage=test
      lint_command: pnpm run -r --aggregate-output --reporter=append-only --no-bail lint
      excluded_jobs: docker
    secrets: inherit
    permissions: write-all
