name: CI-CRON checks

on:
  pull_request: {}
  workflow_dispatch:

jobs:
  call-workflow:
    uses: studiographene/studiographene-reactjs-scans/.github/workflows/cron-ci.yml@feature/pnpm
    with:
      project_name: pulse-data-integration
      apply_suppression: false
    permissions: write-all
