name: StudioGraphene-Dependency-Analytics
on:
  push:
    branches: [dev]
jobs:
  dependency_analytics:
    uses: studiographene/github-action-workflows/.github/workflows/pulse-dependencies-analytics.yml@master
    secrets: inherit
    permissions: write-all