name: StudioGraphene-SAST-Analytics

on:
  push:
    branches: [dev]

jobs:
  call-worflow:
    uses: studiographene/github-action-workflows/.github/workflows/pulse-sast-analytics.yml@fix/PX-1602 # if you want alternatively pin to tag version version
    secrets: inherit


# name: sg-sast-analytics

# on:
#   push:
#     branches: [dev, master, qa, uat, prod]

# jobs:
#   analytics:
#     uses: studiographene/nodejs-ci/.github/workflows/sast-analytics.yml@master
#     secrets: inherit
#     permissions: write-all
